# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.224
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Mod metadata
mod_group=net.mystic.wallpapercraft
mod_id=wallpapercraft
mod_name=Wallpapercraft
mod_license=MIT
mod_authors=Mysticpasta1
mod_description=WallpaperCraft - RePainted
mod_version=1.21.1-1.2.0

# Dependencies
jei_version=19.22.1.316
