modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/Mysticpasta1/Wallpapercraft/issues"
license = "MIT"

[[mods]]
modId = "wallpapercraft"
version = "1.0.0"
displayName = "Wallpapercraft"
credits = "Oliviaoliviasson (textures), toby20_ (planks textures)"
authors = "Mysticpasta1"
description = '''
Wallpapercraft - RePainted
'''

[[dependencies.wallpapercraft]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wallpapercraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wallpapercraft]]
modId = "jei"
mandatory = false
versionRange = "[13.1.0,)"
ordering = "AFTER"
side = "CLIENT"
