modLoader = "javafml"
loaderVersion = "[43,44)"  # Forge 43.x (MC 1.19.2)
issueTrackerURL = "https://github.com/Mysticpasta1/Wallpapercraft/issues"
license = "MIT"

[[mods]]
modId = "wallpapercraft"
version = "1.0.0"
displayName = "Wallpapercraft"
credits = "Oliviaoliviasson (textures), toby20_ (planks textures)"
authors = "Mysticpasta1"
description = '''
Wallpapercraft - RePainted
'''

[[dependencies.wallpapercraft]]
modId = "forge"
mandatory = true
versionRange = "[43,44)"   # keep in the 43.x family
ordering = "NONE"
side = "BOTH"

[[dependencies.wallpapercraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.19.3)"  # 1.19.2 only
ordering = "NONE"
side = "BOTH"

# Optional JEI client dep (for your JEI 11.8.1.1034 plugin)
[[dependencies.wallpapercraft]]
modId = "jei"
mandatory = false
versionRange = "[11.8.1,)"
ordering = "AFTER"
side = "CLIENT"
